// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'models.dart';

// **************************************************************************
// ElModelGenerator
// **************************************************************************

extension ElThemeDataExt on ElThemeData {
  ElThemeData copyWith({
    Color? primary,
    Color? secondary,
    Color? success,
    Color? info,
    Color? warning,
    Color? error,
    Color? bgColor,
    Color? headerColor,
    Color? footerColor,
    Color? sideColor,
    Color? iconColor,
    Color? textColor,
    Color? regularTextColor,
    Color? secondaryTextColor,
    Color? placeholderTextColor,
    Color? disabledTextColor,
    Color? darkerBorderColor,
    Color? darkBorderColor,
    Color? borderColor,
    Color? lightBorderColor,
    Color? lighterBorderColor,
    Color? cardColor,
    Color? selectionColor,
    Color? tooltipColor,
    Color? linkColor,
    Color? linkActiveColor,
  }) {
    return ElThemeData(
      primary: primary ?? this.primary,
      secondary: secondary ?? this.secondary,
      success: success ?? this.success,
      info: info ?? this.info,
      warning: warning ?? this.warning,
      error: error ?? this.error,
      bgColor: bgColor ?? this.bgColor,
      headerColor: headerColor ?? this.headerColor,
      footerColor: footerColor ?? this.footerColor,
      sideColor: sideColor ?? this.sideColor,
      iconColor: iconColor ?? this.iconColor,
      textColor: textColor ?? this.textColor,
      regularTextColor: regularTextColor ?? this.regularTextColor,
      secondaryTextColor: secondaryTextColor ?? this.secondaryTextColor,
      placeholderTextColor: placeholderTextColor ?? this.placeholderTextColor,
      disabledTextColor: disabledTextColor ?? this.disabledTextColor,
      darkerBorderColor: darkerBorderColor ?? this.darkerBorderColor,
      darkBorderColor: darkBorderColor ?? this.darkBorderColor,
      borderColor: borderColor ?? this.borderColor,
      lightBorderColor: lightBorderColor ?? this.lightBorderColor,
      lighterBorderColor: lighterBorderColor ?? this.lighterBorderColor,
      cardColor: cardColor ?? this.cardColor,
      selectionColor: selectionColor ?? this.selectionColor,
      tooltipColor: tooltipColor ?? this.tooltipColor,
      linkColor: linkColor ?? this.linkColor,
      linkActiveColor: linkActiveColor ?? this.linkActiveColor,
    );
  }

  List<Object?> get _props => [
    primary,
    secondary,
    success,
    info,
    warning,
    error,
    bgColor,
    headerColor,
    footerColor,
    sideColor,
    iconColor,
    textColor,
    regularTextColor,
    secondaryTextColor,
    placeholderTextColor,
    disabledTextColor,
    darkerBorderColor,
    darkBorderColor,
    borderColor,
    lightBorderColor,
    lighterBorderColor,
    cardColor,
    selectionColor,
    tooltipColor,
    linkColor,
    linkActiveColor,
  ];
}

extension ElConfigDataExt on ElConfigData {
  ElConfigData copyWith({
    AnimationStyle? animationStyle,
    Duration? duration,
    Duration? fastDuration,
    Map<ElLevelType, double>? rounded,
    double? borderWidth,
    String? fontFamily,
    List<String>? fontFamilyFallback,
    double? fontSize,
    double? iconSize,
    FontWeight? fontWeight,
    FontWeight Function([FontWeight])? fontWeightBuilder,
    ScrollController Function([ElScrollControllerAttrModel])? scrollControllerBuilder,
    Widget Function(BuildContext)? arrowRightBuilder,
    Widget Function(BuildContext)? arrowDownBuilder,
    int? messageDuration,
    int? loadingIndex,
    int? promptIndex,
    int? messageIndex,
    int? toastIndex,
  }) {
    return ElConfigData(
      animationStyle: animationStyle ?? this.animationStyle,
      duration: duration ?? this.duration,
      fastDuration: fastDuration ?? this.fastDuration,
      rounded: rounded ?? this.rounded,
      borderWidth: borderWidth ?? this.borderWidth,
      fontFamily: fontFamily ?? this.fontFamily,
      fontFamilyFallback: fontFamilyFallback ?? this.fontFamilyFallback,
      fontSize: fontSize ?? this.fontSize,
      iconSize: iconSize ?? this.iconSize,
      fontWeight: fontWeight ?? this.fontWeight,
      fontWeightBuilder: fontWeightBuilder ?? this.fontWeightBuilder,
      scrollControllerBuilder: scrollControllerBuilder ?? this.scrollControllerBuilder,
      arrowRightBuilder: arrowRightBuilder ?? this.arrowRightBuilder,
      arrowDownBuilder: arrowDownBuilder ?? this.arrowDownBuilder,
      messageDuration: messageDuration ?? this.messageDuration,
      loadingIndex: loadingIndex ?? this.loadingIndex,
      promptIndex: promptIndex ?? this.promptIndex,
      messageIndex: messageIndex ?? this.messageIndex,
      toastIndex: toastIndex ?? this.toastIndex,
    );
  }

  List<Object?> get _props => [
    animationStyle,
    duration,
    fastDuration,
    rounded,
    borderWidth,
    fontFamily,
    fontFamilyFallback,
    fontSize,
    iconSize,
    fontWeight,
    fontWeightBuilder,
    scrollControllerBuilder,
    arrowRightBuilder,
    arrowDownBuilder,
    messageDuration,
    loadingIndex,
    promptIndex,
    messageIndex,
    toastIndex,
  ];
}
