name: el_dart
description: element dart library.
version: 0.0.12
repository: https://github.com/luoyi58624/el

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  archive: ^4.0.9
  crypto: ^3.0.7
  logger: ^2.7.0
  web: ^1.1.1
  path: ^1.9.1
  uuid: ^4.5.3
  meta: ^1.17.0
  collection: ^1.19.1
  equatable: ^2.0.8
  faker: ^2.2.0

dev_dependencies:
  lints: ^6.0.0
  test: any
