// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'event.dart';

// **************************************************************************
// ElModelGenerator
// **************************************************************************

extension ElEventStyleExt on ElEventStyle {
  ElEventStyle copyWith({
    bool? disabled,
    HitTestBehavior? behavior,
    void Function(PointerDownEvent)? onPointerDown,
    void Function(PointerMoveEvent)? onPointerMove,
    void Function(PointerUpEvent)? onPointerUp,
    void Function(PointerHoverEvent)? onHover,
    void Function(PointerPanZoomStartEvent)? onPointerPanZoomStart,
    void Function(PointerPanZoomUpdateEvent)? onPointerPanZoomUpdate,
    void Function(PointerPanZoomEndEvent)? onPointerPanZoomEnd,
    void Function(PointerSignalEvent)? onPointerSignal,
    void Function(PointerCancelEvent)? onPointerCancel,
    int? tapUpDelay,
    void Function(PointerUpEvent)? onTap,
    void Function(PointerDownEvent)? onTapDown,
    void Function(PointerUpEvent)? onTapUp,
    void Function(PointerDownEvent)? onSecondaryTapDown,
    void Function(PointerUpEvent)? onSecondaryTapUp,
    void Function(PointerDownEvent)? onTertiaryTapDown,
    void Function(PointerUpEvent)? onTertiaryTapUp,
    void Function(PointerDownEvent)? onForwardTapDown,
    void Function(PointerUpEvent)? onForwardTapUp,
    void Function(PointerDownEvent)? onBackTapDown,
    void Function(PointerUpEvent)? onBackTapUp,
    void Function(PointerEvent)? onCancel,
    int? doubleTapInterval,
    void Function(int)? onDoubleTap,
    void Function(double)? onScaleUpdate,
    bool? ignoreStatus,
    bool? longPressFeedback,
    void Function(PointerDownEvent)? onLongPress,
    LongPressGestureRecognizer? longPressGestureRecognizer,
    HitTestBehavior? hoverBehavior,
    MouseCursor? cursor,
    MouseCursor? disabledCursor,
    void Function(PointerEnterEvent)? onEnter,
    void Function(PointerExitEvent)? onExit,
    void Function()? onActivate,
    FocusNode? focusNode,
    FocusNode? parentNode,
    bool? autofocus,
    bool? canRequestFocus,
    bool? skipTraversal,
    bool? descendantsAreFocusable,
    bool? descendantsAreTraversable,
    bool? includeFocusSemantics,
    int? activeThrottle,
    void Function(bool)? onFocusChange,
  }) {
    return ElEventStyle(
      disabled: disabled ?? this.disabled,
      behavior: behavior ?? this.behavior,
      onPointerDown: onPointerDown ?? this.onPointerDown,
      onPointerMove: onPointerMove ?? this.onPointerMove,
      onPointerUp: onPointerUp ?? this.onPointerUp,
      onHover: onHover ?? this.onHover,
      onPointerPanZoomStart: onPointerPanZoomStart ?? this.onPointerPanZoomStart,
      onPointerPanZoomUpdate: onPointerPanZoomUpdate ?? this.onPointerPanZoomUpdate,
      onPointerPanZoomEnd: onPointerPanZoomEnd ?? this.onPointerPanZoomEnd,
      onPointerSignal: onPointerSignal ?? this.onPointerSignal,
      onPointerCancel: onPointerCancel ?? this.onPointerCancel,
      tapUpDelay: tapUpDelay ?? this.tapUpDelay,
      onTap: onTap ?? this.onTap,
      onTapDown: onTapDown ?? this.onTapDown,
      onTapUp: onTapUp ?? this.onTapUp,
      onSecondaryTapDown: onSecondaryTapDown ?? this.onSecondaryTapDown,
      onSecondaryTapUp: onSecondaryTapUp ?? this.onSecondaryTapUp,
      onTertiaryTapDown: onTertiaryTapDown ?? this.onTertiaryTapDown,
      onTertiaryTapUp: onTertiaryTapUp ?? this.onTertiaryTapUp,
      onForwardTapDown: onForwardTapDown ?? this.onForwardTapDown,
      onForwardTapUp: onForwardTapUp ?? this.onForwardTapUp,
      onBackTapDown: onBackTapDown ?? this.onBackTapDown,
      onBackTapUp: onBackTapUp ?? this.onBackTapUp,
      onCancel: onCancel ?? this.onCancel,
      doubleTapInterval: doubleTapInterval ?? this.doubleTapInterval,
      onDoubleTap: onDoubleTap ?? this.onDoubleTap,
      onScaleUpdate: onScaleUpdate ?? this.onScaleUpdate,
      ignoreStatus: ignoreStatus ?? this.ignoreStatus,
      longPressFeedback: longPressFeedback ?? this.longPressFeedback,
      onLongPress: onLongPress ?? this.onLongPress,
      longPressGestureRecognizer: longPressGestureRecognizer ?? this.longPressGestureRecognizer,
      hoverBehavior: hoverBehavior ?? this.hoverBehavior,
      cursor: cursor ?? this.cursor,
      disabledCursor: disabledCursor ?? this.disabledCursor,
      onEnter: onEnter ?? this.onEnter,
      onExit: onExit ?? this.onExit,
      onActivate: onActivate ?? this.onActivate,
      focusNode: focusNode ?? this.focusNode,
      parentNode: parentNode ?? this.parentNode,
      autofocus: autofocus ?? this.autofocus,
      canRequestFocus: canRequestFocus ?? this.canRequestFocus,
      skipTraversal: skipTraversal ?? this.skipTraversal,
      descendantsAreFocusable: descendantsAreFocusable ?? this.descendantsAreFocusable,
      descendantsAreTraversable: descendantsAreTraversable ?? this.descendantsAreTraversable,
      includeFocusSemantics: includeFocusSemantics ?? this.includeFocusSemantics,
      activeThrottle: activeThrottle ?? this.activeThrottle,
      onFocusChange: onFocusChange ?? this.onFocusChange,
    );
  }

  ElEventStyle merge([ElEventStyle? other]) {
    if (other == null) return this;
    return copyWith(
      disabled: other.disabled,
      behavior: other.behavior,
      onPointerDown: other.onPointerDown,
      onPointerMove: other.onPointerMove,
      onPointerUp: other.onPointerUp,
      onHover: other.onHover,
      onPointerPanZoomStart: other.onPointerPanZoomStart,
      onPointerPanZoomUpdate: other.onPointerPanZoomUpdate,
      onPointerPanZoomEnd: other.onPointerPanZoomEnd,
      onPointerSignal: other.onPointerSignal,
      onPointerCancel: other.onPointerCancel,
      tapUpDelay: other.tapUpDelay,
      onTap: other.onTap,
      onTapDown: other.onTapDown,
      onTapUp: other.onTapUp,
      onSecondaryTapDown: other.onSecondaryTapDown,
      onSecondaryTapUp: other.onSecondaryTapUp,
      onTertiaryTapDown: other.onTertiaryTapDown,
      onTertiaryTapUp: other.onTertiaryTapUp,
      onForwardTapDown: other.onForwardTapDown,
      onForwardTapUp: other.onForwardTapUp,
      onBackTapDown: other.onBackTapDown,
      onBackTapUp: other.onBackTapUp,
      onCancel: other.onCancel,
      doubleTapInterval: other.doubleTapInterval,
      onDoubleTap: other.onDoubleTap,
      onScaleUpdate: other.onScaleUpdate,
      ignoreStatus: other.ignoreStatus,
      longPressFeedback: other.longPressFeedback,
      onLongPress: other.onLongPress,
      longPressGestureRecognizer: other.longPressGestureRecognizer,
      hoverBehavior: other.hoverBehavior,
      cursor: other.cursor,
      disabledCursor: other.disabledCursor,
      onEnter: other.onEnter,
      onExit: other.onExit,
      onActivate: other.onActivate,
      focusNode: other.focusNode,
      parentNode: other.parentNode,
      autofocus: other.autofocus,
      canRequestFocus: other.canRequestFocus,
      skipTraversal: other.skipTraversal,
      descendantsAreFocusable: other.descendantsAreFocusable,
      descendantsAreTraversable: other.descendantsAreTraversable,
      includeFocusSemantics: other.includeFocusSemantics,
      activeThrottle: other.activeThrottle,
      onFocusChange: other.onFocusChange,
    );
  }

  List<Object?> get _props => [
    ignoreStatus,
    longPressFeedback,
    onLongPress,
    longPressGestureRecognizer,
    hoverBehavior,
    cursor,
    disabledCursor,
    onEnter,
    onExit,
    onActivate,
    focusNode,
    parentNode,
    autofocus,
    canRequestFocus,
    skipTraversal,
    descendantsAreFocusable,
    descendantsAreTraversable,
    includeFocusSemantics,
    activeThrottle,
    onFocusChange,
  ];
}
